services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  api:
    build:
      context: .
      dockerfile: TravelProject/Dockerfile
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=postgres_db;Username=user;Password=password"

  frontend:
    container_name: travelroutes-frontend
    restart: unless-stopped
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8081
    depends_on:
      - api

volumes:
  postgres_data:
