// One-off: fetch real foot/hiking trail geometry from BRouter (no API key) for
// each mock route's POI waypoints, then print baked [lat,lng] path arrays to
// paste into src/data/mockRoutes.ts. Runtime app stays fully offline.
//
//   node scripts/gen-tracks.mjs
//
// Safe to delete after the geometry is baked in.

const routes = {
  "morskie-oko-rysy": [
    [49.2701, 20.0805], [49.2645, 20.0865], [49.2602, 20.0875],
    [49.2486, 20.0820], [49.2418, 20.0884], [49.2367, 20.0880],
  ],
  "dolina-koscieliska": [
    [49.2767, 19.8732], [49.2680, 19.8704], [49.2640, 19.8682], [49.2566, 19.8645],
  ],
  "giewont-przez-kondracka": [
    [49.2992, 19.9492], [49.2880, 19.9472], [49.2772, 19.9438], [49.2735, 19.9423],
  ],
  "petla-bialego-strazyska": [
    [49.2877, 19.9647], [49.2780, 19.9583], [49.2807, 19.9521], [49.2843, 19.9417], [49.2877, 19.9647],
  ],
};

const R = 6371;
const toRad = (d) => (d * Math.PI) / 180;
function haversineKm(a, b) {
  const dLat = toRad(b[0] - a[0]);
  const dLng = toRad(b[1] - a[1]);
  const s = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(a[0])) * Math.cos(toRad(b[0])) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}
function lengthKm(path) {
  let d = 0;
  for (let i = 1; i < path.length; i++) d += haversineKm(path[i - 1], path[i]);
  return Math.round(d * 10) / 10;
}

async function brouter(waypoints) {
  const lonlats = waypoints.map(([lat, lng]) => `${lng},${lat}`).join("|");
  const url = `https://brouter.de/brouter?lonlats=${lonlats}&profile=hiking-beta&alternativeidx=0&format=geojson`;
  const res = await fetch(url, { headers: { "User-Agent": "travelroutes-dev" } });
  if (!res.ok) throw new Error(`BRouter ${res.status} for ${lonlats}`);
  const json = await res.json();
  const coords = json.features[0].geometry.coordinates; // [lon,lat,ele?]
  // Convert to [lat,lng], round to 5 dp (~1.1 m).
  return coords.map(([lon, lat]) => [Math.round(lat * 1e5) / 1e5, Math.round(lon * 1e5) / 1e5]);
}

import { writeFileSync } from "node:fs";

const blocks = [];
for (const [slug, wps] of Object.entries(routes)) {
  const path = await brouter(wps);
  const lines = [];
  for (let i = 0; i < path.length; i += 4) {
    lines.push("    " + path.slice(i, i + 4).map(([a, b]) => `[${a}, ${b}]`).join(", ") + ",");
  }
  console.log(`${slug} — ${path.length} pts, ~${lengthKm(path)} km (routed)`);
  blocks.push(`  // ${slug} — ${path.length} pts, ~${lengthKm(path)} km\n  "${slug}": [\n${lines.join("\n")}\n  ],`);
}

const out = `// AUTO-GENERATED by scripts/gen-tracks.mjs — do not edit by hand.
// Dense walking-trail geometry sourced once from BRouter (hiking-beta profile,
// OpenStreetMap data). Each entry is the detailed [lat, lng] track that follows
// real paths between a route's POIs. Regenerate with: node scripts/gen-tracks.mjs

export const routeTracks: Record<string, [number, number][]> = {
${blocks.join("\n")}
};
`;

const dest = new URL("../src/data/routeTracks.ts", import.meta.url);
writeFileSync(dest, out);
console.log(`\nWrote ${dest.pathname}`);
